export const CHEESE_BURGER = "CAN I HAVE A CHEESEBURGER?"
export const DARE = "THOSE WHO DARE TO FAIL MISERABLY CAN ACHIEVE GREATLY."
export const SECRETS = "YOUR SECRETS ARE SAFE WITH ME... I WASN'T EVEN LISTENING."