export const SLITHERY_SNAKES =
  'WE ARE SOME SERIOUSLY SLITHERY SNAKES. SO SNEAKY.'
export const HISS = 'HISS...'
export const SECRETS =
  "OF THE MANY FEARSOME BEASTS AND MONSTERS THAT ROAM OUR LAND, THERE IS NONE MORE CURIOUS OR MORE DEADLY THAT THE BASILISK, KNOWN ALSO AS THE KING OF SERPENTS. THIS SNAKE, WHICH MAY REACH GIGANTIC SIZE, AND LIVE MANY HUNDREDS OF YEARS, IS BORN FROM A CHICKEN'S EGG, HATCHED BENEATH A TOAD. ITS METHODS OF KILLING ARE MORE WONDEROUS, FOR ASIDE FROM ITS DEADLY AND VENOMOUS FANGS, THE BASILISK HAS A MURDEROUS STARE, AND ALL WHO ARE FIXED WITH THE BEAM OF ITS EYE SHALL SUFFER INSTANT DEATH. SPIDERS FLEE BEFORE THE BASILISK, FOR IT IS THEIR MORTAL ENEMY, AND THE BASILISK FLEES ONLY FROM THE CROWING OF THE ROOSTER, WHICH IS FATAL TO IT."
